name: shortcode-widget
recipe: wordpress
config:
  php: "8.1"
  webroot: wordpress
  database: pantheon-mariadb
  # Keep it empty, to enable xdebug use `lando xdebug <xdebug mode>` instead
  xdebug: ""
  config:
    php: .lando/php.ini
    database: .lando/mysql.cnf
services:
  appserver:
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
        PROFILER_OUTPUT_DIR: "profiler-output" # If changing this value, change in .gitignore also
      volumes:
        - '.lando/wp-cli.yml:/wp-cli.yml'
        - '.:/app/wordpress/wp-content/plugins/shortcode-widget'
        - '/app/wordpress/wp-content/plugins/shortcode-widget/wordpress'
        - '/app/wordpress/wp-content/plugins/shortcode-widget/node_modules'
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
    build:
      - wp core download --force --skip-content
    run:
      - sleep 5 # For some reason, we have to wait at least a second till database is up.
      - | # Create WordPress config file and add necessary constants and custom config
        wp config create --dbhost=database --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbprefix=wp_ --force
      - wp config set WP_DISABLE_FATAL_ERROR_HANDLER true --raw
      - wp config set WP_DEBUG true --raw
      - wp config set WP_DEBUG_LOG true --raw
      - wp config set WP_DEBUG_DISPLAY false --raw
      - wp config set AUTOMATIC_UPDATER_DISABLED true --raw
      - wp config set DISALLOW_FILE_EDIT true --raw
      - wp config set WP_ENVIRONMENT_TYPE 'local'
      - | # Let's check if WordPress is not installed, then install it
        if ! wp core is-installed; then
          wp core install --url=https://$LANDO_APP_NAME.$LANDO_DOMAIN \
            --title=$LANDO_APP_NAME \
            --admin_user=admin \
            --admin_password=password \
            --admin_email=me@gagan.pro \
            --skip-email
          wp theme install --activate twentytwentyone
        fi
tooling:
  xdebug:
    description: Loads Xdebug in the selected mode.
    cmd:
      - appserver: /app/.lando/xdebug.sh
    user: root
  node:
    service: appserver
  npm:
    service: appserver