dist: xenial

cache:
  directories:
    - $HOME/.cache/composer/files

language:
  - php
  
notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  # Speed up build time by disabling Xdebug.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - if [[ ! -z "$WP_VERSION" ]] ; then
        bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
        composer global require "phpunit/phpunit=5.7.*"
    fi

script:
  - if [[ ! -z "$WP_VERSION" ]] ; then
        phpunit
        WP_MULTISITE=1 phpunit
    fi

stages:
  - verify
  - test

env:
    global:
        - PATH=$PATH:/home/travis/.config/composer/vendor/bin

jobs:
    fast_finish: true
    include:
        - stage: verify
          php: 7.2
          before_install: phpenv config-rm xdebug.ini || echo 'No xdebug config.'
          before_script: false
          install:
              - composer global require dealerdirect/phpcodesniffer-composer-installer wp-coding-standards/wpcs --update-no-dev
          script:
              - phpcs -i
              - phpcs
